### ISSUE TITLE
Catalog Problems for Jing

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#313]
When trying to validate with `susedoc5.rnc`, the RNC file contains the following line:

``` rnc
include "http://www.docbook.org/xml/5.1/rng/docbookxi.rnc" {
 ...
}
```

Although there is a catalog entry which points to the correct path, when executing Jing with the `-C` option, it gives the following Java traceback:

```
$ daps-jing -C /etc/xml/docbook_5.xml \
   -c /local/doc/suse-xsl/schema/rng/0.9/susedoc5.rnc \
   /local/doc/GH/doc-sle/build/.profiled/x86_64_zseries_power_sled/MAIN.SLEDS.xml
[... output pruned ...]
Exception in thread "main" java.lang.NullPointerException
        at org.apache.xml.resolver.helpers.PublicId.normalize(PublicId.java:58)
        at org.apache.xml.resolver.Catalog.resolveLocalPublic(Catalog.java:1579)
        at org.apache.xml.resolver.Catalog.resolvePublic(Catalog.java:1509)
        at com.thaiopensource.resolver.catalog.CatalogResolver.resolve(CatalogResolver.java:79)
        at com.thaiopensource.resolver.SequenceResolver.resolve(SequenceResolver.java:18)
        at com.thaiopensource.resolver.xml.sax.SAX$EntityResolverImpl.resolveEntity(SAX.java:184)
        at org.apache.xerces.util.EntityResolver2Wrapper.resolveEntity(Unknown Source)
        at org.apache.xerces.xinclude.XIncludeHandler.handleIncludeElement(Unknown Source)
        at org.apache.xerces.xinclude.XIncludeHandler.emptyElement(Unknown Source)
        at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at com.thaiopensource.validate.ValidationDriver.validate(ValidationDriver.java:160)
        at com.thaiopensource.relaxng.util.Driver.doMain(Driver.java:154)
        at com.thaiopensource.relaxng.util.Driver.main(Driver.java:35)
```

We should find a way to either deal with the above exception or use a workaround.

Some possible solutions:
1. Fix the above Java exception.
2. Use system links and avoid any URIs in `include` statements.
3. "Merge" DocBook5 and SUSEDoc into one file.
4. Something else...?

@fsundermeyer What do you prefer?

**Comment by tomschr** [comment]
This worked for me:
- Replace any URI in the `include` element of `susedoc5.rnc` to its base name; for example, `include "docbookxi.rnc" {...}`
- Create a link in the same directory as `susedoc5.rnc`. The link must point to `/usr/share/xml/docbook/schema/rng/5.1/docbookxi.rnc` (SUSE).
- Validate

**Comment by tomschr** [comment]
Ok, this is the solution which we need to integrate in our RPM packages:

## Preparations

Commit https://github.com/openSUSE/daps/commit/749999079 used the base name in the `include` statement. You don't have to change the RNC schema.

## Packaging Hints
- Use `preREQ` for `docbook_5` and `xmlcatalog`

## Steps
1. Install the `susedoc5.rnc` schema in the usual location.
2. Determine the location of the DocBook5.1 schema (`docbookxi.rnc`):
   
   ```
   $ xmlcatalog /etc/xml/catalog http://docbook.org/xml/5.1/rng/docbookxi.rnc
   file:/usr/share/xml/docbook/schema/rng/5.1/docbookxi.rnc
   ```
   
   Use the result from the `xmlcatalog` call.
   If it fails, fallback to DocBook 5.0 and repeat this step with this URI: http://docbook.org/xml/5.0/rng/docbookxi.rnc``
3. Create a link from `docbookxi.rnc` to the directory from step 2. The link must be in the same directory than the `susedoc5.rnc` file.

**Comment by tomschr** [comment]
@fsundermeyer I think, I've found another promising solution, [rnginline](https://pypi.python.org/pypi/rnginline/):

>  rnginline is a Python library and command-line tool for loading multi-file RELAX NG schemas from arbitary URLs, and flattening them into a single RELAX NG schema.

You pass the tool the `susedoc5.rng` file and it creates **one, single** RNG file without any includes! That would mean, you don't have to depend on the original DocBook source!

Some rough tests looks promising!

Maybe we could use both: Use the approach above _and_ deliver the "flat" structure, without any includes.

What do you think?

**Comment by tomschr** [comment]
@fsundermeyer Created an RPM package [`python3-rnginline`](https://build.opensuse.org/package/show/home:thomas-schraitle/python3-rnginline). At the moment it stays in my home project, but will be moved into `devel:languages:python3` in the future.

Furthermore, I've updated the [README](https://github.com/openSUSE/suse-xsl/blob/develop/schema/README) in `suse-xsl` repo. I've described the details about the process there.

**Comment by tomschr** [comment]
Related to openSUSE/suse-xsl#237 (renaming schema files)
