### ISSUE TITLE
Creating PDF not possible

### ISSUE THREAD

**Issue by MartinKoeditz** [openSUSE/daps#549]
Hi,

I recently updated my server from OpenSuse 42.3 to 15.0 and 15.1. **daps** was also updated from 2.4.0 to 3.0.0. But now **daps** cannot create PDF output.

Here is the output:
```
user@newserver:/srv/www/htdocs/docs05.syndesk.de> daps -v3 -d SynDesk.DC pdf
---------------

        DAPS VERSION: 3.0.0

             DOC_DIR: /srv/www/htdocs/docs05.syndesk.de
           BUILD_DIR: /srv/www/htdocs/docs05.syndesk.de/build
            DAPSROOT: /usr/share/daps
             DOCCONF: /srv/www/htdocs/docs05.syndesk.de/SynDesk.DC
                BOOK: SynDesk.DC

           PROFILING: On

     DOCBOOK_VERSION: 5
        DOCBOOK5_RNG: /usr/share/xml/docbook/schema/rng/5.1/docbookxi.rng
        DBSTYLE_VERS: snapshot

           STYLEROOT: /usr/share/xml/docbook/stylesheet/nwalsh5/current
      STYLEROOT_VERS: Not available
   FB_STYLEROOT_VERS: Not available
            EPUB_CSS:
            HTML_CSS:

       PDF FORMATTER: fop
   FORMATTER VERSION: FOP Version 2.1
   FORMATTER WRAPPER: /usr/share/daps/libexec/daps-fop
    FORMATTER CONFIG:

            MAKE_CMD: /usr/bin/remake -f /usr/share/daps/make/selector.mk --debug=b -j1 pdf
       XSLTPROCESSOR: /usr/bin/xsltproc
   XML_CATALOG_FILES: /etc/xml/catalog

---------------

„make“-Steuerdateien werden gelesen...
Updating makefiles...
Updating goal targets...
 Die Datei „pdf“ existiert nicht.
   Die Datei „/srv/www/htdocs/docs05.syndesk.de/build/SynDesk.DC/SynDesk.DC_color_de.pdf“ existiert nicht.
     Die Datei „/srv/www/htdocs/docs05.syndesk.de/build/.tmp/SynDesk.DC-fop_color_de.fo“ existiert nicht.
    Das Target „/srv/www/htdocs/docs05.syndesk.de/build/.tmp/SynDesk.DC-fop_color_de.fo“ muss neu erzeugt werden.
/usr/share/daps/libexec/daps-xslt --xinclude --param "show.comments=0" --param "generate.permalink=0" --param "ulink.show=1" --stringparam "draft.mode=no" --stringparam "styleroot=/usr/share/xml/docbook/stylesheet/nwalsh5/current/" --param "format.print=0" --stringparam "img.src.path=/srv/www/htdocs/docs05.syndesk.de/build/.images/color/" --param "fop1.extensions=1" --param "xep.extensions=0"   \
      --stringparam "converter.name=DAPS" --stringparam "converter.version=3.0.0" --stringparam "converter.url=https://opensuse.github.io/daps"   \
     --output /srv/www/htdocs/docs05.syndesk.de/build/.tmp/SynDesk.DC-fop_color_de.fo --stylesheet /usr/share/xml/docbook/stylesheet/nwalsh5/current/fo/docbook.xsl \
    --file /srv/www/htdocs/docs05.syndesk.de/build/.profiled/noprofile/SynDesk-docs05.xml /usr/bin/xsltproc  \
    ;
Making portrait pages on USletter paper (8.5inx11in)
Unrecognized unit of measure: ,5cm.
    Die Zieldatei „/srv/www/htdocs/docs05.syndesk.de/build/.tmp/SynDesk.DC-fop_color_de.fo“ wurde erfolgreich aktualisiert.
     Die Datei „/srv/www/htdocs/docs05.syndesk.de/build/.tmp/images“ existiert nicht.
    Das Target „/srv/www/htdocs/docs05.syndesk.de/build/.tmp/images“ muss neu erzeugt werden.
(cd /srv/www/htdocs/docs05.syndesk.de/build/.tmp && ln -sf /usr/share/xml/docbook/stylesheet/nwalsh5/current/images)
    Die Zieldatei „/srv/www/htdocs/docs05.syndesk.de/build/.tmp/images“ wurde erfolgreich aktualisiert.
  Das Target „/srv/www/htdocs/docs05.syndesk.de/build/SynDesk.DC/SynDesk.DC_color_de.pdf“ muss neu erzeugt werden.
(cd /srv/www/htdocs/docs05.syndesk.de/build/.tmp/ && /usr/share/daps/libexec/daps-fop /srv/www/htdocs/docs05.syndesk.de/build/.tmp/SynDesk.DC-fop_color_de.fo /srv/www/htdocs/docs05.syndesk.de/build/SynDesk.DC/SynDesk.DC_color_de.pdf  )
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.CharBuffer.rewind()Ljava/nio/CharBuffer;
        at org.apache.fop.fo.FOText.characters(FOText.java:132)
        at org.apache.fop.fo.FObjMixed.characters(FObjMixed.java:74)
        at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.characters(FOTreeBuilder.java:388)
        at org.apache.fop.fo.FOTreeBuilder.characters(FOTreeBuilder.java:136)
        at com.sun.org.apache.xml.internal.serializer.ToXMLSAXHandler.characters(ToXMLSAXHandler.java:546)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.characters(AbstractSAXParser.java:546)
        at com.sun.org.apache.xerces.internal.xinclude.XIncludeHandler.characters(XIncludeHandler.java:1131)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:455)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transformIdentity(TransformerImpl.java:659)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:728)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:343)
        at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:285)
        at org.apache.fop.cli.InputHandler.renderTo(InputHandler.java:115)
        at org.apache.fop.cli.Main.startFOP(Main.java:186)
        at org.apache.fop.cli.Main.main(Main.java:216)
/usr/share/daps/make/pdf.mk:239: *** [/srv/www/htdocs/docs05.syndesk.de/build/SynDesk.DC/SynDesk.DC_color_de.pdf] Error 1

#0  /srv/www/htdocs/docs05.syndesk.de/build/SynDesk.DC/SynDesk.DC_color_de.pdf at /usr/share/daps/make/pdf.mk:238
#1  pdf at /usr/share/daps/make/pdf.mk:179
```

Maybe someone can help.

Regards
Martin

**Comment by fsundermeyer** [comment]
Could you please check which java version you are using?

`zypper se -i java`

Should be 10, or 11 IIRC - 8 does not work with FOP (a missing xmlgraphics-fop dependency). HTH

**Comment by MartinKoeditz** [comment]
Yes, that's it! 
Thank you.
